model:
  rnn_type: lstm
  hidden_size: 256
  hidden_layers: 1
checkpointing:
  continue_from: ''
  checkpoint: true
  checkpoint_per_iteration: 0
  save_n_recent_models: 5
  best_val_model_name: deepspeech_final.pth
  load_auto_checkpoint: false
  save_folder: /content/drive/MyDrive/Optimization/hessian_v1/models
training:
  no_cuda: false
  finetune: false
  seed: 123456
  dist_backend: nccl
  epochs: 20
data:
  train_manifest: ../libri_train_manifest.csv
  val_manifest: ../libri_val_manifest.csv
  batch_size: 20
  num_workers: 4
  labels_path: labels.json
  spect:
    sample_rate: 16000
    window_size: 0.02
    window_stride: 0.01
    window: hamming
  augmentation:
    speed_volume_perturb: false
    spec_augment: false
    noise_dir: ''
    noise_prob: 0.4
    noise_min: 0.0
    noise_max: 0.5
augmentation:
  speed_volume_perturb: false
  spec_augment: false
  noise_dir: ''
  noise_prob: 0.4
  noise_min: 0.0
  noise_max: 0.5
apex:
  opt_level: O1
  loss_scale: 1
visualization:
  id: DeepSpeech training
  visdom: false
  tensorboard: true
  wandb: true
  log_dir: /content/drive/MyDrive/Optimization/hessian_v1/visualize/deepspeech_final
  log_params: false